# New section

In [4]:
import pandas as pd
import numpy as np

In [61]:
df = pd.read_csv("spotify_songs_dataset.csv")

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   song_id           50000 non-null  object
 1   song_title        50000 non-null  object
 2   artist            50000 non-null  object
 3   album             50000 non-null  object
 4   genre             50000 non-null  object
 5   release_date      50000 non-null  object
 6   duration          45000 non-null  float64
 7   popularity        50000 non-null  int64
 8   stream            50000 non-null  int64
 9   language          47500 non-null  object
 10  explicit_content  50000 non-null  object
 11  label             50000 non-null  object
 12  composer          50000 non-null  object
 13  producer          50000 non-null  object
 14  collaboration     15000 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 5.7+ MB

In [68]:
df['release_date'] = pd.to_datetime(df['release_date'], format='%Y-%m-%d', errors='coerce')
print(df)
print(df.dtypes)

       song_id               song_title             artist              album  \
0       SP0001  Space executive series.       Sydney Clark              What.
1       SP0002     Price last painting.  Connor Peters DDS   Nature politics.
2       SP0003                   Piece.         Anna Keith             Visit.
3       SP0004     Power industry your.    Zachary Simpson  Behavior evening.
4       SP0005      Food animal second.  Christopher Mcgee             Front.
...        ...                      ...                ...                ...
49995  SP49996      Event push do body.   Shelley Robinson         Wrong cup.
49996  SP49997      Share clearly role.   Jennifer Kennedy     That actually.
49997  SP49998      Wonder type simply.       Hailey Walsh    South Democrat.
49998  SP49999                 Company.       Leah Coleman             Front.
49999  SP50000              Woman plan.       Daniel Brown             Three.

            genre release_date  duration  popularity    stream language  \
0      Electronic   1997-11-08     282.0          42  35055874  English
1      Electronic   2015-05-10     127.0          50   9249527  English
2             Pop   2024-07-08       NaN          10  76669110  English
3         Hip-Hop   2022-08-15     214.0          86  34732016  English
4             Pop   2023-03-05     273.0          63  96649372  English
...           ...          ...       ...         ...       ...      ...
49995         Pop   1999-05-26     272.0          38  25078113  Spanish
49996        Folk   2016-08-21     355.0          62  29908581   Korean
49997         Pop   1997-02-28     207.0          38  75864558  Spanish
49998  Electronic   1996-07-15     266.0          10  41817978  English
49999         Pop   2009-01-19     188.0          38  19182847  English

      explicit_content             label           composer  \
0                  Yes           Def Jam       Amy Hatfield
1                  Yes   Universal Music      Jason Gregory
2                  Yes   Universal Music       Rachel Lopez
3                   No        Sony Music          Thomas Li
4                  Yes           Def Jam        Adam Wagner
...                ...               ...                ...
49995               No             Indie     Melissa Wilson
49996              Yes  Atlantic Records       Timothy Rice
49997               No  Atlantic Records         Susan Diaz
49998               No        Sony Music   Dr. Zachary Bell
49999               No             Indie  Madeline Williams

                producer collaboration
0         Jeffrey Weaver           NaN
1          Kenneth White           NaN
2           Jason Barnes           NaN
3      Mrs. Becky Palmer           NaN
4          Beverly Baker           NaN
...                  ...           ...
49995    Leslie Ferguson   Daniel Cruz
49996   Randall Martinez           NaN
49997    Katrina Fleming           NaN
49998        Pam Schultz           NaN
49999        Carla Fritz           NaN

[50000 rows x 15 columns]
song_id                     object
song_title                  object
artist                      object
album                       object
genre                       object
release_date        datetime64[ns]
duration                   float64
popularity                   int64
stream                       int64
language                    object
explicit_content            object
label                       object
composer                    object
producer                    object
collaboration               object
dtype: object

In [69]:
# Convert the column to datetime and remove the time part
#df['release_date'] = pd.to_datetime(df['release_date']).dt.date

df['release_date'] = df['release_date'].dt.normalize()
print(df)
print(df.dtypes)

       song_id               song_title             artist              album  \
0       SP0001  Space executive series.       Sydney Clark              What.
1       SP0002     Price last painting.  Connor Peters DDS   Nature politics.
2       SP0003                   Piece.         Anna Keith             Visit.
3       SP0004     Power industry your.    Zachary Simpson  Behavior evening.
4       SP0005      Food animal second.  Christopher Mcgee             Front.
...        ...                      ...                ...                ...
49995  SP49996      Event push do body.   Shelley Robinson         Wrong cup.
49996  SP49997      Share clearly role.   Jennifer Kennedy     That actually.
49997  SP49998      Wonder type simply.       Hailey Walsh    South Democrat.
49998  SP49999                 Company.       Leah Coleman             Front.
49999  SP50000              Woman plan.       Daniel Brown             Three.

            genre release_date  duration  popularity    stream language  \
0      Electronic   1997-11-08     282.0          42  35055874  English
1      Electronic   2015-05-10     127.0          50   9249527  English
2             Pop   2024-07-08       NaN          10  76669110  English
3         Hip-Hop   2022-08-15     214.0          86  34732016  English
4             Pop   2023-03-05     273.0          63  96649372  English
...           ...          ...       ...         ...       ...      ...
49995         Pop   1999-05-26     272.0          38  25078113  Spanish
49996        Folk   2016-08-21     355.0          62  29908581   Korean
49997         Pop   1997-02-28     207.0          38  75864558  Spanish
49998  Electronic   1996-07-15     266.0          10  41817978  English
49999         Pop   2009-01-19     188.0          38  19182847  English

      explicit_content             label           composer  \
0                  Yes           Def Jam       Amy Hatfield
1                  Yes   Universal Music      Jason Gregory
2                  Yes   Universal Music       Rachel Lopez
3                   No        Sony Music          Thomas Li
4                  Yes           Def Jam        Adam Wagner
...                ...               ...                ...
49995               No             Indie     Melissa Wilson
49996              Yes  Atlantic Records       Timothy Rice
49997               No  Atlantic Records         Susan Diaz
49998               No        Sony Music   Dr. Zachary Bell
49999               No             Indie  Madeline Williams

                producer collaboration
0         Jeffrey Weaver           NaN
1          Kenneth White           NaN
2           Jason Barnes           NaN
3      Mrs. Becky Palmer           NaN
4          Beverly Baker           NaN
...                  ...           ...
49995    Leslie Ferguson   Daniel Cruz
49996   Randall Martinez           NaN
49997    Katrina Fleming           NaN
49998        Pam Schultz           NaN
49999        Carla Fritz           NaN

[50000 rows x 15 columns]
song_id                     object
song_title                  object
artist                      object
album                       object
genre                       object
release_date        datetime64[ns]
duration                   float64
popularity                   int64
stream                       int64
language                    object
explicit_content            object
label                       object
composer                    object
producer                    object
collaboration               object
dtype: object

In [71]:
df.describe()

                     release_date      duration    popularity        stream
count                       50000  45000.000000  50000.000000  5.000000e+04
mean   2009-10-01 17:25:40.224000    239.659178     50.783440  5.019183e+07
min           1994-10-06 00:00:00     33.000000      1.000000  1.899000e+03
25%           2002-03-25 18:00:00    206.000000     26.000000  2.523311e+07
50%           2009-09-25 00:00:00    240.000000     51.000000  5.042169e+07
75%           2017-04-19 00:00:00    273.000000     76.000000  7.519064e+07
max           2024-10-05 00:00:00    433.000000    100.000000  9.999913e+07
std                           NaN     50.136727     28.948749  2.893624e+07

In [72]:
df['duration'] = df['duration'].fillna(df['duration'].mean())

In [73]:
df['language'] = df['language'].fillna(df['language'].mode()[0])

In [76]:
df = df.drop('collaboration', axis=1)

In [77]:
df.describe()

                     release_date      duration    popularity        stream
count                       50000  50000.000000  50000.000000  5.000000e+04
mean   2009-10-01 17:25:40.224000    239.659178     50.783440  5.019183e+07
min           1994-10-06 00:00:00     33.000000      1.000000  1.899000e+03
25%           2002-03-25 18:00:00    210.000000     26.000000  2.523311e+07
50%           2009-09-25 00:00:00    239.659178     51.000000  5.042169e+07
75%           2017-04-19 00:00:00    269.000000     76.000000  7.519064e+07
max           2024-10-05 00:00:00    433.000000    100.000000  9.999913e+07
std                           NaN     47.563823     28.948749  2.893624e+07

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   song_id           50000 non-null  object
 1   song_title        50000 non-null  object
 2   artist            50000 non-null  object
 3   album             50000 non-null  object
 4   genre             50000 non-null  object
 5   release_date      50000 non-null  datetime64[ns]
 6   duration          50000 non-null  float64
 7   popularity        50000 non-null  int64
 8   stream            50000 non-null  int64
 9   language          50000 non-null  object
 10  explicit_content  50000 non-null  object
 11  label             50000 non-null  object
 12  composer          50000 non-null  object
 13  producer          50000 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(10)
memory usage: 5.3+ MB

In [82]:
cols_to_clean = ['song_id', 'song_title', 'artist', 'album','genre', 'language', 'explicit_content', 'label', 'composer', 'producer' ]

# Remove special characters from selected columns

for col in cols_to_clean:
    df[col] = df[col].str.replace(r'[^A-Za-z0-9- ]+', '', regex=True)


print(df).head()

       song_id              song_title             artist             album  \
0       SP0001  Space executive series       Sydney Clark              What
1       SP0002     Price last painting  Connor Peters DDS   Nature politics
2       SP0003                   Piece         Anna Keith             Visit
3       SP0004     Power industry your    Zachary Simpson  Behavior evening
4       SP0005      Food animal second  Christopher Mcgee             Front
...        ...                     ...                ...               ...
49995  SP49996      Event push do body   Shelley Robinson         Wrong cup
49996  SP49997      Share clearly role   Jennifer Kennedy     That actually
49997  SP49998      Wonder type simply       Hailey Walsh    South Democrat
49998  SP49999                 Company       Leah Coleman             Front
49999  SP50000              Woman plan       Daniel Brown             Three

            genre release_date    duration  popularity    stream language  \
0      Electronic   1997-11-08  282.000000          42  35055874  English
1      Electronic   2015-05-10  127.000000          50   9249527  English
2             Pop   2024-07-08  239.659178          10  76669110  English
3         Hip-Hop   2022-08-15  214.000000          86  34732016  English
4             Pop   2023-03-05  273.000000          63  96649372  English
...           ...          ...         ...         ...       ...      ...
49995         Pop   1999-05-26  272.000000          38  25078113  Spanish
49996        Folk   2016-08-21  355.000000          62  29908581   Korean
49997         Pop   1997-02-28  207.000000          38  75864558  Spanish
49998  Electronic   1996-07-15  266.000000          10  41817978  English
49999         Pop   2009-01-19  188.000000          38  19182847  English

      explicit_content             label           composer          producer
0                  Yes           Def Jam       Amy Hatfield    Jeffrey Weaver
1                  Yes   Universal Music      Jason Gregory     Kenneth White
2                  Yes   Universal Music       Rachel Lopez      Jason Barnes
3                   No        Sony Music          Thomas Li  Mrs Becky Palmer
4                  Yes           Def Jam        Adam Wagner     Beverly Baker
...                ...               ...                ...               ...
49995               No             Indie     Melissa Wilson   Leslie Ferguson
49996              Yes  Atlantic Records       Timothy Rice  Randall Martinez
49997               No  Atlantic Records         Susan Diaz   Katrina Fleming
49998               No        Sony Music    Dr Zachary Bell       Pam Schultz
49999               No             Indie  Madeline Williams       Carla Fritz

[50000 rows x 14 columns]

AttributeError: 'NoneType' object has no attribute 'head'

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   song_id           50000 non-null  object
 1   song_title        50000 non-null  object
 2   artist            50000 non-null  object
 3   album             50000 non-null  object
 4   genre             50000 non-null  object
 5   release_date      50000 non-null  datetime64[ns]
 6   duration          50000 non-null  float64
 7   popularity        50000 non-null  int64
 8   stream            50000 non-null  int64
 9   language          50000 non-null  object
 10  explicit_content  50000 non-null  object
 11  label             50000 non-null  object
 12  composer          50000 non-null  object
 13  producer          50000 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(10)
memory usage: 5.3+ MB

In [86]:
df.to_excel('cleaned_dataset.xlsx', index=False)